 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     

     steps:
       - checkout
       - run:
           name: "npm install"
           command: npm install           
       - run: 
           name: "grunt build"
             - command: |
                cd \src\buildscripts\methodfitness
               yarn grunt
