// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=CannibalCoder.cloudapp.net;Initial Catalog=MethodFitness_PROD;User ID=methodfitness;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`

using FluentMigrator;

namespace Migrations
{
    [Migration(20050)]
    public class Alter_TrainerMetric_Sproc_20050 : Migration
    {
        public override void Up()
        {
            string sql = System.IO.File.ReadAllText(@"src\dbfluentmigration\Alter_TrainerMetric_Sproc_20050.sql");
            Execute.Sql(sql);
        }

        public override void Down()
        {
            
        }
    }
}


